version: '3.8'

services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - server1
      - server2
      - server3
    networks:
      - app-network

  server1:
    build:
      context: .
      dockerfile: Dockerfile
    command: node backend/server1.js
    environment:
      - NODE_ENV=production
      - PORT=5003
      - MONGODB_URI=mongodb+srv://narayanaudayagiri88:narayanaudayagiri88@cluster0.xfb8w.mongodb.net/synergy
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    env_file:
      - .env
    networks:
      - app-network

  server2:
    build:
      context: .
      dockerfile: Dockerfile
    command: node backend/server2.js
    environment:
      - NODE_ENV=production
      - PORT=5003
      - MONGODB_URI=mongodb+srv://narayanaudayagiri88:narayanaudayagiri88@cluster0.xfb8w.mongodb.net/synergy
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    env_file:
      - .env
    networks:
      - app-network

  server3:
    build:
      context: .
      dockerfile: Dockerfile
    command: node backend/server3.js
    environment:
#      - NODE_ENV=${NODE_ENV}
#      - PORT=5003
#      - MONGODB_URI=${MONGODB_URI}
#      - REDIS_HOST=${REDIS_HOST}
#      - REDIS_PORT=${REDIS_PORT}
#      - REDIS_PASSWORD=${REDIS_PASSWORD}
#      - GEMINI_API_KEY=${GEMINI_API_KEY}
#      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - NODE_ENV=production
      - PORT=5003
      - MONGODB_URI=mongodb+srv://narayanaudayagiri88:narayanaudayagiri88@cluster0.xfb8w.mongodb.net/synergy
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    env_file:
      - .env
    networks:
      - app-network

  frontend:
    build:
      context: ./FinalFrontend
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=${NODE_ENV}
      - VITE_API_URL= https://lingualeap-backend.onrender.com
#      - VITE_API_URL=http://localhost:5001
    env_file:
      - .env
    networks:
      - app-network

  redis:
    image: redis:latest
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis_data:/data
    networks:
      - app-network

volumes:
  redis_data:

networks:
  app-network:
    driver: bridge