global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'backend'
    static_configs:
      - targets: ['backend:5001']

  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']